name: emojis
description: Emojis for Dart! This package contain all unicode 16.0 emojis (2024)!
version: 3.1.0
homepage:  https://github.com/i-Naji/emojis

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  test: ^1.19.3
  pedantic: ^1.11.1
